### PR TITLE
Add contact information for Nicholas Tietz-Sokolsky

### PR DESCRIPTION
**Pull request by ntietz**

### CODE REVIEW

**Comment by StefPac** [comment]
Hi Nicholas, I would suggest to keep the affiliations down to one ( I have multiple too ), in order to keep the list simple. What do you think? If you agree, would you mind updating the PR? Also, very minor request, can you keep the raw table aligned? Many thanks!

**Comment by ntietz** [comment]
Keeping one affiliation is fine with me, although I'm not sure what advantage it has (in my case, I have two "jobs" which I split my time between, so it's really a toss-up which I picked; I picked the one more likely to exist in 6 months).

While table alignment is a minor request right now, it will become a much more difficult task as we add folks to the table -- any time someone has a longer name (like mine), it requires bumping all the cells.

**Comment by ntietz** [comment]
We might want to consider maintaining a CSV file instead, and using a tool to convert the CSV to Markdown -- it would be easier to maintain. I can open a PR for that if you want.

**Comment by ntietz** [comment]
@StefPac I think this should be all ready to merge, but let me know if there's any problem with it. And let me know if there's anything I can do to make maintenance of this repo easier!

**Comment by StefPac** [comment]
Hi @nietz thanks much for this. Merging the PR now, and yes, definitely feel free to propose something more efficient, if you have the time!

**Pull request merged**
